name: Run Tests

on:
  push:
    branches: [ '**' ]  # This will match all branches
  pull_request:
    branches: [ '**' ]  # This will match all branches
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame numpy
        pip install -e .
    
    - name: Run tests
      run: |
        python -m pytest orbital/tests/ -v
    